# Generated by Django 2.1.5 on 2019-02-01 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import lactolyse.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lactolyse', '0003_add_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConconiMeasurement',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('power', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConconiTestAnalyses',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateField(auto_now_add=True)),
                (
                    'report',
                    models.FileField(
                        upload_to=lactolyse.models.generate_lactate_threshold_name
                    ),
                ),
                ('result', models.IntegerField(null=True)),
                (
                    'athlete',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='lactolyse.Athlete',
                    ),
                ),
                (
                    'contributor',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='conconimeasurement',
            name='analyses',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='lactolyse.ConconiTestAnalyses',
            ),
        ),
    ]
